apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: fiap-observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
      annotations:
        fiap.tech-challenge/observability-config-checksum: "${observability_config_checksum}"
    spec:
      containers:
        - name: loki
          image: grafana/loki:latest
          ports:
            - { name: http, containerPort: 3100 }
          volumeMounts:
            - name: data
              mountPath: /loki
          resources:
            requests: { cpu: 50m, memory: 128Mi }
            limits: { cpu: 500m, memory: 512Mi }
      volumes:
        - name: data
          emptyDir: {}
