apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: newrelic-license
  namespace: fiap-observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-store
    kind: SecretStore
  target:
    name: newrelic-license
    creationPolicy: Owner
  data:
    - secretKey: license-key
      remoteRef:
        key: fiap-newrelic-license
        property: license-key
